//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSC_EntityDAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Order()
        {
            this.Billings = new HashSet<Billing>();
            this.OrderProducts = new HashSet<OrderProduct>();
        }
    
        public int OrderIdPk { get; set; }
        public Nullable<int> StoreIdFk { get; set; }
        public Nullable<int> CustomerIdFk { get; set; }
        public Nullable<int> EmployeeIdFk { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int NoOfItems { get; set; }
        public decimal Amount { get; set; }
        public string OrderCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billings { get; set; }
        public virtual Customer Customer { get; set; }
        public virtual Employee Employee { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProduct> OrderProducts { get; set; }
        public virtual Store Store { get; set; }
    }
}
