//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OMS.DataAccessLayer.Entity_Muni.EntityFrameWork_Muni
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.OrderItem = new HashSet<OrderItem>();
            this.Returns = new HashSet<Returns>();
        }
    
        public int OrderIdpk { get; set; }
        public string InvoiceNumber { get; set; }
        public int WareHouseIdfk { get; set; }
        public int CustomerIdfk { get; set; }
        public System.DateTime OrderDate { get; set; }
        public Nullable<decimal> NoOfItems { get; set; }
        public int PaymentStatusIdfk { get; set; }
        public Nullable<decimal> TotalAmount { get; set; }
    
        public virtual customers customers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderItem> OrderItem { get; set; }
        public virtual WareHouse WareHouse { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Returns> Returns { get; set; }
    }
}
