//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillingIdPk { get; set; }
        public string BillingNumber { get; set; }
        public Nullable<int> OrderIdFK { get; set; }
        public string PaymentMode { get; set; }
        public string BillingDate { get; set; }
        public string Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
