//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntityDataAccess.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderProduct
    {
        public int OrderProductIdPk { get; set; }
        public Nullable<int> OrderIdFk { get; set; }
        public Nullable<int> ProductIdFk { get; set; }
        public string Quantity { get; set; }
        public string PriceUnit { get; set; }
        public string Amount { get; set; }
    
        public virtual Orders Orders { get; set; }
        public virtual ProductMaster ProductMaster { get; set; }
    }
}
