//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSC.EntityDAL_venky.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Billing = new HashSet<Billing>();
            this.OrderProducts = new HashSet<OrderProducts>();
        }
    
        public int OrderIdPk { get; set; }
        public Nullable<int> StoreIdFk { get; set; }
        public Nullable<int> CustomerIdFk { get; set; }
        public Nullable<int> EmployeeIdFk { get; set; }
        public System.DateTime OrderDate { get; set; }
        public int NoOfItems { get; set; }
        public decimal Amount { get; set; }
        public string OrderCode { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Billing> Billing { get; set; }
        public virtual Customers Customers { get; set; }
        public virtual Employees Employees { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderProducts> OrderProducts { get; set; }
        public virtual Stores Stores { get; set; }
    }
}
