//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EnityDataAccessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Inventory
    {
        public int InventoryIdpk { get; set; }
        public int WarehouseIdfk { get; set; }
        public int ProductIdfk { get; set; }
        public decimal AvailableQuantity { get; set; }
        public decimal PricePerUnit { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string Remianingquantity { get; set; }
    
        public virtual Product Product { get; set; }
        public virtual WareHouse WareHouse { get; set; }
    }
}
