//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RSCEntityDSAL.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Billing
    {
        public int BillIdPk { get; set; }
        public string BillNumber { get; set; }
        public Nullable<int> OrderIdFk { get; set; }
        public string PaymentMode { get; set; }
        public System.DateTime BillingDate { get; set; }
        public decimal Amount { get; set; }
    
        public virtual Order Order { get; set; }
    }
}
